# Generated by Django 4.1 on 2022-08-09 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=10)),
                ('accent', models.BooleanField()),
                ('slide', models.BooleanField()),
                ('octave', models.CharField(max_length=20)),
                ('timing', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('waveform', models.BooleanField()),
                ('cutoff_dial', models.IntegerField()),
                ('resonance_dial', models.IntegerField()),
                ('envelope_dial', models.IntegerField()),
                ('decay_dial', models.IntegerField()),
                ('attack_dial', models.IntegerField()),
                ('tempo_dial', models.IntegerField()),
                ('tempo_entered', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('steps', models.ManyToManyField(related_name='patterns', to='patterns.step')),
            ],
        ),
    ]
