# Generated by Django 4.1 on 2022-08-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
