# Generated by Django 4.1 on 2022-08-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_step_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
