# Generated by Django 4.1 on 2022-08-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_alter_pattern_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='steps',
            field=models.ManyToManyField(blank=True, related_name='patterns', to='patterns.step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='note',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='octave',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='timing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
